using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Kapitan.Kubernetes;

namespace Kapitan.Kubernetes.Networking.V1alpha3
{
    public partial class ListenerMatch
    {
        /** <summary>Match a specific listener by its name. The listeners generated by Pilot are typically named as IP:Port.</summary> */
        public string name { get; set; }
        /** <summary>The service port/gateway port to which traffic is being sent/received. If not specified, matches all listeners. Even though inbound listeners are generated for the instance/pod ports, only service ports should be used to match listeners.</summary> */
        public int portNumber { get; set; }
        /** <summary>Instead of using specific port numbers, a set of ports matching a given service's port name can be selected. Matching is case insensitive. Not implemented. $hide_from_docs</summary> */
        public string portName { get; set; }
        /** <summary>For listeners with multiple filter chains (e.g., inbound listeners on sidecars with permissive mTLS, gateway listeners with multiple SNI matches), the filter chain match can be used to select a specific filter chain to patch.</summary> */
        public FilterChainMatch filterChain { get; set; }
    }
}