using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Kapitan.Kubernetes;

namespace Kapitan.Kubernetes.Networking.V1alpha3
{
    public partial class RouteMatch
    {
        /** <summary>The Route objects generated by default are named as "default". Route objects generated using a virtual service will carry the name used in the virtual service's HTTP routes.</summary> */
        public string name { get; set; }
        /** <summary>Action refers to the route action taken by Envoy when a http route matches.</summary> */
        public Action action { get; set; }
    }
}